GET http://localhost:3001/api/persons/1 HTTP/1.1

###

GET http://localhost:3001/api/persons HTTP/1.1


###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
	"name": "rash",
	"number": "003-200241"
}

###

DELETE  http://localhost:3001/api/persons/5 HTTP/1.1
