GET http://localhost:3001/api/people/1 HTTP/1.1

###

GET http://localhost:3001/api/people HTTP/1.1


###

POST http://localhost:3001/api/people HTTP/1.1
content-type: application/json

{
	"name": "brooo it's work",
	"number": "0X3-2XXXXXX1",
	"userId": "652c25d33c524b43925aecb3"
}

###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "rash0x6964",
    "name": "rash",
    "password": "salainen"
}


###

PUT http://localhost:3001/api/people/65144a5aa509f07c26ef28bc HTTP/1.1
content-type: application/json

{
	"name": "yey updateed",
	"number": "000-000000"
}

###

DELETE  http://localhost:3001/api/people/652c288635a1f929443a5d3d HTTP/1.1
